In [2]:
import numpy as np
a = [[11,12,13], [21,22,23], [31,32,33]]

A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [3]:
A.ndim

2

In [5]:
A.shape  # number of list and size of list

(3, 3)

In [6]:
A.size

9

In [8]:
A : [[A[0,0], A[0,1], A[0,2]], [A[1,0], A[1,1], A[1,2]], [A[2,0], A[2,1], A[2,2]]]
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [9]:
A[1][2]

23

In [10]:
A[0, 0:2]

array([11, 12])

In [11]:
A[0:2, 2] # takes 0 and 1's second elements

array([13, 23])

In [14]:
# dot
A = np.array([[0, 1, 1], [1, 0, 1]])
B = np.array([[1,1], [1,1], [-1,1]])

C = np.dot(A,B)
C

array([[0, 2],
       [0, 2]])

In [15]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,2],[2,2]])
Z=np.dot(X,Y)

In [16]:
Z

array([[2, 2],
       [2, 2]])

In [17]:
X=np.array([[1,0,1],[2,2,2]]) 
out=X[0,1:3]
out

array([0, 1])